COMMON_CONFIG_PATH: "dataset_creation/common_config.yaml"
DATASET_NAME: "RM_C_S"

TYPE: "color"  # Options: "color", "gray"

TRAIN_SIZE: 60000
VAL_SIZE: 10000
TEST_SIZE: 10000

C_HEIGHT: 224
C_WIDTH: 224
MIN_NUM_LABELS: 1
MAX_NUM_LABELS: 5

CHANGE_SIZE: True
CHANGE_BRIGHTNESS: False
RATIO_LIM_SIZE: [1.0, 3.0]
RATIO_LIM_BRIGHTNESS: [0.1, 1.0]

MIN_MARGIN: 10
MAX_ROT: 11.5
